name: dev release

on:
  push:
    branches: [dev]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install

      - name: Build
        env:
          NEXT_PUBLIC_COUPANG_PARTNERS_API_ACCESS_KEY: ${{ secrets.COUPANG_PARTNERS_API_ACCESS_KEY }}
          NEXT_PUBLIC_COUPANG_PARTNERS_API_SECRET_KEY: ${{ secrets.COUPANG_PARTNERS_API_SECRET_KEY }}
          NEXT_PUBLIC_NODE_ENV: 'development'
        run: |
          yarn run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy
        env:
          NEXT_PUBLIC_COUPANG_PARTNERS_API_ACCESS_KEY: ${{ secrets.COUPANG_PARTNERS_API_ACCESS_KEY }}
          NEXT_PUBLIC_COUPANG_PARTNERS_API_SECRET_KEY: ${{ secrets.COUPANG_PARTNERS_API_SECRET_KEY }}
          NEXT_PUBLIC_NODE_ENV: 'development'
        run: |
          yarn run devDeploy

  notification:
    runs-on: ubuntu-latest
    needs: release
    if: always()
    steps:
      - name: Send a Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # TENQUBE_FE deploy
          channel-id: "C07SR98RWE4"
          slack-message: "${{ github.repository }} 개발 배포 ${{ needs.release.result == 'success' &&  '성공' || '실패'}}\nURL: https://dev-aipicks-avabuzz.tenqube.com/\nChangeLog: https://github.com/TENQUBE/aipicks-avabuzz/releases"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}